name: ${project.name}
main: net.bitjump.bukkit.subwhitelister.SubWhitelister
version: ${project.version}
author: Bitjump
api-version: "1.12"
commands:
    sw:
        description: The SubWhitelister master command.
        usage: /<command> [subcommand]
        aliases: [subwhitelister]
permissions:
    subwhitelister.*:
        default: op
        children:
            subwhitelister.commands.*: true
            subwhitelister.exempt: true
    subwhitelister.commands.*:
        default: false
        children:
            subwhitelister.commands.export: true
            subwhitelister.commands.list: true
            subwhitelister.commands.reload: true
            subwhitelister.commands.toggle: true
    subwhitelister.commands.export:
        default: false       
    subwhitelister.commands.list:
        default: false
    subwhitelister.commands.reload:
        default: false
    subwhitelister.commands.toggle:
        default: false
    subwhitelister.exempt:
        default: false